/**
 * ExportButton Component
 * Export simplified text as PDF or copy to clipboard
 */
"use client";

import React, { useState } from "react";
import { Download, Copy, Check, FileText } from "lucide-react";

interface ExportButtonProps {
  content: string;
  title?: string;
}

export default function ExportButton({ content, title = "NeuroLearn Notes" }: ExportButtonProps) {
  const [copied, setCopied] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [showMenu, setShowMenu] = useState(false);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      console.error("Failed to copy:", error);
      alert("Failed to copy to clipboard");
    }
  };

  const handleExportPDF = async () => {
    setIsExporting(true);
    try {
      // Dynamic import of html2pdf
      const html2pdf = (await import("html2pdf.js")).default;
      
      // Create a styled container for PDF
      const container = document.createElement("div");
      container.innerHTML = `
        <div style="font-family: Arial, sans-serif; padding: 20px; max-width: 800px;">
          <h1 style="color: #3b82f6; margin-bottom: 10px;">${title}</h1>
          <p style="color: #6b7280; font-size: 12px; margin-bottom: 20px;">
            Generated by NeuroLearn on ${new Date().toLocaleDateString()}
          </p>
          <hr style="border: 1px solid #e5e7eb; margin-bottom: 20px;" />
          <div style="line-height: 1.8; font-size: 14px; color: #374151;">
            ${content.split('\n').map(p => `<p style="margin-bottom: 12px;">${p}</p>`).join('')}
          </div>
        </div>
      `;
      
      const options = {
        margin: 10,
        filename: `${title.toLowerCase().replace(/\s+/g, '_')}_${Date.now()}.pdf`,
        image: { type: "jpeg", quality: 0.98 },
        html2canvas: { scale: 2 },
        jsPDF: { unit: "mm", format: "a4", orientation: "portrait" },
      };
      
      // @ts-ignore - html2pdf.js types are incomplete
      await html2pdf().from(container).set(options).save();
    } catch (error) {
      console.error("PDF export failed:", error);
      // Fallback: Download as text file
      downloadAsText();
    } finally {
      setIsExporting(false);
      setShowMenu(false);
    }
  };

  const downloadAsText = () => {
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${title.toLowerCase().replace(/\s+/g, '_')}_${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setShowMenu(false);
  };

  return (
    <div className="relative">
      <button
        onClick={() => setShowMenu(!showMenu)}
        className="flex items-center gap-2 bg-blue-500 hover:bg-blue-600 text-white font-medium py-2 px-4 rounded-lg transition"
      >
        <Download size={18} />
        Export
      </button>

      {showMenu && (
        <div className="absolute right-0 mt-2 w-48 bg-white dark:bg-gray-800 rounded-lg shadow-xl z-50 overflow-hidden">
          <button
            onClick={handleExportPDF}
            disabled={isExporting}
            className="w-full flex items-center gap-3 px-4 py-3 hover:bg-gray-100 dark:hover:bg-gray-700 transition text-left"
          >
            <FileText size={18} className="text-red-500" />
            <span className="text-gray-700 dark:text-gray-300">
              {isExporting ? "Exporting..." : "Save as PDF"}
            </span>
          </button>
          
          <button
            onClick={downloadAsText}
            className="w-full flex items-center gap-3 px-4 py-3 hover:bg-gray-100 dark:hover:bg-gray-700 transition text-left"
          >
            <FileText size={18} className="text-blue-500" />
            <span className="text-gray-700 dark:text-gray-300">Save as Text</span>
          </button>
          
          <button
            onClick={handleCopy}
            className="w-full flex items-center gap-3 px-4 py-3 hover:bg-gray-100 dark:hover:bg-gray-700 transition text-left border-t border-gray-200 dark:border-gray-700"
          >
            {copied ? (
              <>
                <Check size={18} className="text-green-500" />
                <span className="text-green-600 dark:text-green-400">Copied!</span>
              </>
            ) : (
              <>
                <Copy size={18} className="text-gray-500" />
                <span className="text-gray-700 dark:text-gray-300">Copy to Clipboard</span>
              </>
            )}
          </button>
        </div>
      )}
    </div>
  );
}
